version: '3'
services:
  postgres:
    container_name: taskapp_pg
    image: postgres
    expose:
      - 5432
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=taskapp
      - POSTGRES_PASSWORD=password
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
  taskapp-server:
    container_name: taskapp_server
    build:
      context: ../taskapp-server
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      - PG_CONNECTION_STRING=postgres://postgres:password@postgres:5432/taskapp
      - PORT=8080
    ports:
      - '8080:8080'
    volumes:
      - ../taskapp-server/src:/code/src
  taskapp-client:
    container_name: taskapp_client
    build:
      context: ../taskapp-client
      dockerfile: Dockerfile
    depends_on:
      - taskapp-server
    ports:
      - '3000:3000'
    volumes:
      - ../taskapp-client/src:/code/src
volumes:
  pg_data:
